src/Entity/Departement.php
<?php

namespace App\Entity;

use App\Repository\DepartementRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use function Symfony\Component\String\s;

/**
 * Notre classe principale 
 * @ORM\Entity(repositoryClass=DepartementRepository::class)
 */
class Departement
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $code;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $departement_nom_uppercase;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $departement_slug;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $departement_nom_soundex;

    /**
     * @ORM\OneToMany(targetEntity=Annonces::class, mappedBy="departement")
     */
    private $annonces;

    public function __construct()
    {
        $this->villes = new ArrayCollection();
        $this->annonces = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getCode(): ?int
    {
        return $this->code;
    }

    public function setCode(int $code): self
    {
        $this->code = $code;

        return $this;
    }

    public function getDepartementNomUppercase(): ?string
    {
        return $this->departement_nom_uppercase;
    }

    public function setDepartementNomUppercase(string $departement_nom_uppercase): self
    {
        $this->departement_nom_uppercase = $departement_nom_uppercase;

        return $this;
    }

    public function getDepartementSlug(): ?string
    {
        return $this->departement_slug;
    }

    public function setDepartementSlug(string $departement_slug): self
    {
        $this->departement_slug = $departement_slug;

        return $this;
    }

    public function getDepartementNomSoundex(): ?string
    {
        return $this->departement_nom_soundex;
    }

    public function setDepartementNomSoundex(string $departement_nom_soundex): self
    {
        $this->departement_nom_soundex = $departement_nom_soundex;

        return $this;
    }

    public function getDepartementCode(): ?string
    {
        return $this->departement_code;
    }

    public function setDepartementCode(string $departement_code): self
    {
        $this->departement_code = $departement_code;

        return $this;
    }

    public function getDepartementNom(): ?string
    {
        return $this->departement_nom;
    }

    public function setDepartementNom(string $departement_nom): self
    {
        $this->departement_nom = $departement_nom;

        return $this;
    }
    public function __toString()
    {
        return (string)$this->departement_nom_soundex;
    }

    /**
     * @return Collection|Annonces[]
     */
    public function getAnnonces(): Collection
    {
        return $this->annonces;
    }

    public function addAnnonce(Annonces $annonce): self
    {
        if (!$this->annonces->contains($annonce)) {
            $this->annonces[] = $annonce;
            $annonce->setDepartement($this);
        }

        return $this;
    }

    public function removeAnnonce(Annonces $annonce): self
    {
        if ($this->annonces->contains($annonce)) {
            $this->annonces->removeElement($annonce);
            // set the owning side to null (unless already changed)
            if ($annonce->getDepartement() === $this) {
                $annonce->setDepartement(null);
            }
        }

        return $this;
    }

}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Cocur\Slugify\Slugify;
use DateTimeInterface;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @ORM\HasLifecycleCallbacks()
 * @UniqueEntity(fields={"email"}, message="Une autre utilisateur possède déjà cet email, veillez utiliser un autre.")
  */
class User implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="LE prenom ne peut pas être vide !")
     */
    private $firstName;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Le nom ne peut pas être vide !")
     */
    private $lastName;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Email(message="Il faut entrer une adresse email valide !")
     */
    private $email;

    /**
     * @var string
     * @ORM\Column(type="string", length=100)
     */
    private $picture;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $hash;
    /**
     * @Assert\EqualTo(propertyPath="hash", message="Les mots de passe ne sont pas identiques !")
     */
    public $confirmPassword;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min=6, max=70, minMessage="Le titre doit faire 6 caractères minimum",
     *maxMessage="Le titre ne doit pas dépasser 70 caractères !")
     */
    private $intro;

    /**
     * @ORM\Column(type="text")
     * @Assert\Length(min=6, max=155, minMessage="Le titre doit faire 6 caractères minimum",
     *maxMessage="Le titre ne doit pas dépasser 155 caractères !")
     */
    private $presentation;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\Column(type="datetime")
     * @var DateTimeInterface|null
     */

    private $updated_at;

    /**
     * @ORM\OneToMany(targetEntity=Annonces::class, mappedBy="author", orphanRemoval=true)
     */
    private $annonces;

    /**
     * @ORM\ManyToMany(targetEntity=Role::class, mappedBy="users")
     */
    private $usersRoles;





    /**
     * Permet d'initialiser le slug avant la persistence
     * @ORM\PrePersist()
     * @ORM\PreUpdate()
     */
    public function initializeSlug(){
        if (empty($this->slug)){
            $slugify = new Slugify();
            $this->slug = $slugify->slugify($this->getFirstName());
        }
    }
    /**
     * @ORM\PrePersist()
     */
    public function updateDate(){

        if (empty($this->updated_at)){
            $this->updated_at = new \DateTime();
        }
    }

    public function __construct()
    {
        $this->annonces = new ArrayCollection();
        $this->usersRoles = new ArrayCollection();
        $this->achats = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(string $lastName): self
    {
        $this->lastName = $lastName;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }


    public function getHash(): ?string
    {
        return $this->hash;
    }

    public function setHash(string $hash): self
    {
        $this->hash = $hash;

        return $this;
    }

    public function getIntro(): ?string
    {
        return $this->intro;
    }

    public function setIntro(string $intro): self
    {
        $this->intro = $intro;

        return $this;
    }

    public function getPresentation(): ?string
    {
        return $this->presentation;
    }

    public function setPresentation(string $presentation): self
    {
        $this->presentation = $presentation;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    /**
     * @return Collection|Annonces[]
     */
    public function getAnnonces(): Collection
    {
        return $this->annonces;
    }

    public function addAnnonce(Annonces $annonce): self
    {
        if (!$this->annonces->contains($annonce)) {
            $this->annonces[] = $annonce;
            $annonce->setAuthor($this);
        }

        return $this;
    }

    public function removeAnnonce(Annonces $annonce): self
    {
        if ($this->annonces->contains($annonce)) {
            $this->annonces->removeElement($annonce);
            // set the owning side to null (unless already changed)
            if ($annonce->getAuthor() === $this) {
                $annonce->setAuthor(null);
            }
        }

        return $this;
    }

    public function getUpdatedAt(): ?DateTimeInterface
    {
        return $this->updated_at;
    }


    public function setUpdatedAt(DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    /**
     * @return string
     */
    public function getPicture()
    {
        return $this->picture;
    }

    /**
     * @param string $picture
     * @return User
     */
    public function setPicture(string $picture): User
    {
        $this->picture = $picture;
        return $this;
    }


    public function getRoles(){
        $roles = $this->usersRoles->map(function ($role){
            return $role->getTitle();
        })->toArray();
        $roles[]= 'ROLE_USER';
        return $roles;
    }

    public function getPassword(){
        return $this->hash;
    }

    public function getSalt(){}

    public function getUsername(){
        return $this->email;
    }

    public function eraseCredentials(){}

    public function __toString()
    {
        return (string)$this->getFullName();
    }

    /**
     * Permet de concaténer le firname et le lasname de l'utilisateur à fois
     * @return string
     */
    public function getFullName(){
        return "{$this->firstName} {$this->lastName}";
    }

    /**
     * @return Collection|Role[]
     */
    public function getUsersRoles(): Collection
    {
        return $this->usersRoles;
    }

    public function addUsersRole(Role $usersRole): self
    {
        if (!$this->usersRoles->contains($usersRole)) {
            $this->usersRoles[] = $usersRole;
            $usersRole->addUser($this);
        }

        return $this;
    }

    public function removeUsersRole(Role $usersRole): self
    {
        if ($this->usersRoles->contains($usersRole)) {
            $this->usersRoles->removeElement($usersRole);
            $usersRole->removeUser($this);
        }

        return $this;
    }


}

src/Form/AnnoncesType.php
<?php

namespace App\Form;

use App\Entity\Annonces;
use App\Entity\Departement;
use App\Entity\Regions;
use DateTime;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\MoneyType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class AnnoncesType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title', TextType::class,[
                'label'=> 'Titre',
                'attr'=>[
                    'placeholder'=>'Un petit titre en quelques mots pour votre annonce'
                ]
            ])
            ->add('typeConcours')
            ->add('content', TextareaType::class,[
                'label'=>'Contenu de l\'annonce',
                'attr'=>[
                    'placeholder'=>'Le contenu de votre annonce !'
                ]
            ])

            ->add('image', FileType::class, [
                'data_class' => null,
                'label' =>'Photo de l\'affiche',
                'attr'=>[
                    'placeholder'=>'Selectionner une photo principale pour votre affiche !',
                ]
            ])
            ->add('description', TextType::class, [
                'mapped' => false,
                'required' => false,
                'attr'=>[
                    'placeholder'=>'Petite description pour la photo de votre affiche',
                ]
            ])
            ->add('adImages', FileType::class, [

                'multiple' => true,
                'mapped' => false,
                'required' => false,
                'data_class' => null,
                'label'=> 'Photos pour le slide',
                'attr'=>[
                    'placeholder'=>'Selectionner 1 ou plusieurs pour photos affiche (4 max) !',
                ]

            ])
            ->add('region', EntityType::class,[
                'class' => Regions::class,
            ])
            ->add('departement',EntityType::class,[
                 'class'=> Departement::class,
//                    'placeholder'=>'Selectionner le departement !'
                ]
            )
            ->add('createdAt', DateTimeType::class,[
                'widget' => 'single_text',
                'label'=>'Date du concours',
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Annonces::class,
        ]);
    }
}

templates/annonces/_delete_form.html.twig
<form class="ml-3" method="post" action="{{ path('annonces_delete', {'id': ads.id}) }}"
      onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ ads.id) }}">
    <button class="btn btn-danger mt-2">
        <i class="fas fa-trash"></i>
    </button>
</form>

templates/annonces/_form.html.twig
{% block body %}
    <div class="container m-auto">
        {{ form_start(form,{'attr': {'novalidate': 'novalidate'}}) }}
        {{ form_widget(form) }}
        <p>
            {% if app.request.attributes.get('_route') == 'annonces_edit' %}
        <h3>Images</h3>
        {% for image in ads.images %}
          <p > <img class="image_border" src="{{ asset('/uploads/' ~ image.url) }}" alt="images" width="150"></p>
        {% endfor %}
        {% else %}
            <p class="alert alert-warning"> Pas de photos !</p>
        {% endif %}
        </p>
        <button class="btn btn-primary">{{ button_label|default('Save') }}</button>
        {{ form_end(form) }}
    </div>
{% endblock %}


{% block javascripts %}
    <script src="/js/images.js"></script>

{% endblock %}

templates/annonces/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Annonces{% endblock %}

{% block body %}
    <div class="container ">
        <h1>Edit Annonces</h1>

        <div class="row">
            <p>{{ include('annonces/_form.html.twig', {'button_label': 'Update'}) }}</p>
            {{ include('annonces/_delete_form.html.twig') }}
        </div>
    </div>
{% endblock %}

{% block javascripts %}
    <script src="{{ asset('js/images.js') }}"></script>
{% endblock %}

templates/annonces/index.html.twig
{% block title %}Annonces!{% endblock %}
{% extends "base.html.twig" %}

{% block body %}

    <div class="container text-justify">
        <h1 class="my-3">Voici nos annonces pertinentes</h1>

        <div class="row">
            {% for ad in ads %}
                {% set url = path ('annonces_show', {'slug' : ad.slug}) %}

                <div class="col-md-4">
                    <div class="card badge-light mb-3">
                        <div class="card-header text-center">
                           {{ ad.title }} prévu pour <strong>{{ ad.createdAt | date('d/m/Y à I:m')}}</strong> à {{ ad.departement.departementNomUppercase }}
                            dans la région de <strong>{{ ad.region.name }}</strong>  <br>
                            <small>Pas encore noté</small>
                        </div>
                        <a href="{{ url }}">
                            <img src="/uploads/{{ ad.image }}" alt="{{ ad.author.fullName }}"
                                 style="width:100% ; height:250px ;display:block">
                        </a>
                        <div class="card-body">
                            <a href="{{ url }}">
                                <h4 class="card-title">{{ ad.title }} </h4>
                            </a>
                            <p class="card-text">{{ ad.content | raw}}</p>
                            <a class="btn btn-outline-primary"
                               href="{{ path('annonces_show', {'slug': ad.slug}) }} "><i
                                        class="fas fa-eye"></i></a>
        {# <a href="{{ path('achat',{'slug': ad.slug }) }}" class="btn btn-dark"><i class="fas fa-shopping-cart"></i></a>#}
                            {% if app.user and app.user == ad.author %}
                                <a class="btn btn-outline-info"
                                   href="{{ path('annonces_edit', {'slug': ad.slug}) }}">edit</a>
                            {% endif %}

                        </div>
                    </div>
                </div>
            {% else %}
                <p class=" alert alert-warning">Pas d'annonces pour l'instant, revenez plutard !</p>
            {% endfor %}
        </div>
        <p><a class="btn btn-primary" href="{{ path('annonces_new') }}">Create new</a></p>
    </div>
{% endblock %}

templates/annonces/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Annonces{% endblock %}

{% block body %}
   <div class="containertext-light mt-3">
       <h1 class="text-center text-info">Create new Annonces</h1>

       {{ include('annonces/_form.html.twig') }}

       <p class="backtolist"><a class="btn btn-danger mt-2" href="{{ path('annonces_index') }}">back to list</a></p>
   </div>
{% endblock %}

templates/annonces/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Annonces{% endblock %}

{% block body %}
    <h1 class="text-center">Annonces</h1>
    <div class="ad-title text-success bg-white"
         style="background-image: url('/uploads/{{ ads.image }}')">
        <div class="container">
            <h1>{{ ads.title }}</h1>
            <p>{{ ads.content | raw }}</p>
            <p class="h2">
                <strong>{{ ads.departement.departementNomUppercase }}</strong>
                prévu pour <strong>{{ ads.createdAt | date('d/m/Y à I:m') }}</strong>.
            </p>
            {% if app.user and app.user == ads.author %}
                <p class="text-center"><a class="btn btn-outline-primary"
                href="{{ path('annonces_edit', {'slug':ads.slug})}}">
                        <i class="fas fa-edit"></i></a>
                </p>
            {% else %}
                <p class="text-center">
                    <a class="btn btn-outline-primary">
{#                       href="{{ path('achat', {'slug':ads.slug}) }}">#}
                        <i class="fas fa-shopping-cart"></i>
                    </a>
                </p>
            {% endif %}
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-md-8 mb-3 text-justify">
                {{ ads.content | raw }}
                <div id="carouselExampleIndicators"
                     class="carousel slide col-lg-9 col-md-8 col-sm-8" data-ride="carousel">
                    <ol class="carousel-indicators">
                        {% for image in ads.images %}
                            <li data-target="#carouselExampleIndicators"
                                data-slide-to="{{ loop.index0 }}" {% if loop.first %} class="active" {% endif %}></li>
                        {% endfor %}
                    </ol>
                    <div class="carousel-inner">
                        {% for image in ads.images %}
                            <div class="carousel-item {% if loop.first %} active {% endif %}">
                                <a href="/uploads/{{ image.url }}">
                                    <img class="d-block w-100" src="/uploads/{{ image.url }}"
                                         alt="first slide">
                                </a>
                                <div class="carousel-caption d-none d-md-block">
                                    <h5>{{ ads.title }}</h5>
                                    <p>{{ image.description | raw}}</p>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button"
                       data-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button"
                       data-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>
                </div>
                {# fin corrousel#}
                {# fin corrousel#}
                <hr class="alert-info">

            </div>

            <div class="col mt-5">
                <div class="row mb-3 align-items-center">
                    {% set a = ads.author %}
                    <div class="col-4">
                        <img class="image_border" src="/usersimages/{{ a.picture }}"
                             alt="Image du vendeur" class="float-left mr-3">
                    </div>
                    <div class="row">
                        <div class="col">
                            <h3>{{ a.fullName }}</h3>
                            <span class="badge badge-primary">{{ ads.id | length }} annonce(s)</span>
                        </div>
                    </div>
                    <p>{{ a.presentation | raw}}</p>
                </div>
            </div>

        </div>
    </div>
    {% if app.user and app.user == ads.author %}
        <div class="row ml-5">
            <div class="col-4">
                <a class="btn bg-info" href="{{ path('annonces_index') }}">Go back</a>
                <a class="btn btn-primary" href="{{ path('annonces_edit', {'slug': ads.slug}) }}">edit</a>
                {{ include('annonces/_delete_form.html.twig') }}
            </div>
        </div>
    {% endif %}
{% endblock %}