src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Cocur\Slugify\Slugify;
use DateTimeInterface;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @ORM\HasLifecycleCallbacks()
 * @UniqueEntity(fields={"email"}, message="Une autre utilisateur possède déjà cet email, veillez utiliser un autre.")
  */
class User implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="LE prenom ne peut pas être vide !")
     */
    private $firstName;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Le nom ne peut pas être vide !")
     */
    private $lastName;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Email(message="Il faut entrer une adresse email valide !")
     */
    private $email;

    /**
     * @var string
     * @ORM\Column(type="string", length=100)
     */
    private $picture;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $hash;
    /**
     * @Assert\EqualTo(propertyPath="hash", message="Les mots de passe ne sont pas identiques !")
     */
    public $confirmPassword;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min=6, max=70, minMessage="Le titre doit faire 6 caractères minimum",
     *maxMessage="Le titre ne doit pas dépasser 70 caractères !")
     */
    private $intro;

    /**
     * @ORM\Column(type="text")
     * @Assert\Length(min=6, max=155, minMessage="Le titre doit faire 6 caractères minimum",
     *maxMessage="Le titre ne doit pas dépasser 155 caractères !")
     */
    private $presentation;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\Column(type="datetime")
     * @var DateTimeInterface|null
     */

    private $updated_at;

    /**
     * @ORM\OneToMany(targetEntity=Annonces::class, mappedBy="author", orphanRemoval=true)
     */
    private $annonces;

    /**
     * @ORM\ManyToMany(targetEntity=Role::class, mappedBy="users")
     */
    private $usersRoles;





    /**
     * Permet d'initialiser le slug avant la persistence
     * @ORM\PrePersist()
     * @ORM\PreUpdate()
     */
    public function initializeSlug(){
        if (empty($this->slug)){
            $slugify = new Slugify();
            $this->slug = $slugify->slugify($this->getFirstName());
        }
    }
    /**
     * @ORM\PrePersist()
     */
    public function updateDate(){

        if (empty($this->updated_at)){
            $this->updated_at = new \DateTime();
        }
    }

    public function __construct()
    {
        $this->annonces = new ArrayCollection();
        $this->usersRoles = new ArrayCollection();
        $this->achats = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(string $lastName): self
    {
        $this->lastName = $lastName;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }


    public function getHash(): ?string
    {
        return $this->hash;
    }

    public function setHash(string $hash): self
    {
        $this->hash = $hash;

        return $this;
    }

    public function getIntro(): ?string
    {
        return $this->intro;
    }

    public function setIntro(string $intro): self
    {
        $this->intro = $intro;

        return $this;
    }

    public function getPresentation(): ?string
    {
        return $this->presentation;
    }

    public function setPresentation(string $presentation): self
    {
        $this->presentation = $presentation;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    /**
     * @return Collection|Annonces[]
     */
    public function getAnnonces(): Collection
    {
        return $this->annonces;
    }

    public function addAnnonce(Annonces $annonce): self
    {
        if (!$this->annonces->contains($annonce)) {
            $this->annonces[] = $annonce;
            $annonce->setAuthor($this);
        }

        return $this;
    }

    public function removeAnnonce(Annonces $annonce): self
    {
        if ($this->annonces->contains($annonce)) {
            $this->annonces->removeElement($annonce);
            // set the owning side to null (unless already changed)
            if ($annonce->getAuthor() === $this) {
                $annonce->setAuthor(null);
            }
        }

        return $this;
    }

    public function getUpdatedAt(): ?DateTimeInterface
    {
        return $this->updated_at;
    }


    public function setUpdatedAt(DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    /**
     * @return string
     */
    public function getPicture()
    {
        return $this->picture;
    }

    /**
     * @param string $picture
     * @return User
     */
    public function setPicture(string $picture): User
    {
        $this->picture = $picture;
        return $this;
    }


    public function getRoles(){
        $roles = $this->usersRoles->map(function ($role){
            return $role->getTitle();
        })->toArray();
        $roles[]= 'ROLE_USER';
        return $roles;
    }

    public function getPassword(){
        return $this->hash;
    }

    public function getSalt(){}

    public function getUsername(){
        return $this->email;
    }

    public function eraseCredentials(){}

    public function __toString()
    {
        return (string)$this->getFullName();
    }

    /**
     * Permet de concaténer le firname et le lasname de l'utilisateur à fois
     * @return string
     */
    public function getFullName(){
        return "{$this->firstName} {$this->lastName}";
    }

    /**
     * @return Collection|Role[]
     */
    public function getUsersRoles(): Collection
    {
        return $this->usersRoles;
    }

    public function addUsersRole(Role $usersRole): self
    {
        if (!$this->usersRoles->contains($usersRole)) {
            $this->usersRoles[] = $usersRole;
            $usersRole->addUser($this);
        }

        return $this;
    }

    public function removeUsersRole(Role $usersRole): self
    {
        if ($this->usersRoles->contains($usersRole)) {
            $this->usersRoles->removeElement($usersRole);
            $usersRole->removeUser($this);
        }

        return $this;
    }


}

src/Form/UserType.php
<?php

namespace App\Form;

use App\Entity\User;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class UserType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('firstName')
            ->add('lastName')
            ->add('email')
            ->add('hash', PasswordType::class)
            ->add('confirmPassword', PasswordType::class)
            ->add('intro')
            ->add('presentation', TextType::class)
            ->add('picture', FileType::class,[
                'mapped' =>false,
                'required' => false
                ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => User::class,
        ]);
    }
}

src/Controller/UserController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Form\UserType;
use App\Repository\UserRepository;
use App\Service\Pagination;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;

/**
 *
 * @Route("/user")
 */
    class UserController extends AbstractController
    {
        private $passwordEncoder;

        public function __construct(UserPasswordEncoderInterface $passwordEncoder){
         $this->passwordEncoder = $passwordEncoder;
    }

        /**
         * @Route("/{page<\d+>?1}", name="user_index", methods={"GET"})
         * @Security("is_granted('ROLE_ADMIN')")
         * @param UserRepository $userRepository
         * @param $page
         * @param Pagination $pagination
         * @return Response
         */
    public function index(UserRepository $userRepository, $page, Pagination $pagination): Response
    {
        $pagination->setEntityClass(User::class)->setPage($page);
        return $this->render('user/index.html.twig', [
            'users' => $userRepository->findAll(),
            'pagination' => $pagination
        ]);
    }

    /**
     * @Route("/new", name="user_new", methods={"GET","POST"})
     * @param Request $request
     * @return Response
     */
    public function new(Request $request): Response
    {
        $user = new User();
        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            //On récupère les données du formulaire
            $image = $form->get('picture')->getData();
            //on choisit le nom de l'image avec u identifiant unique et gardant le l'extension
            $url = md5(uniqid()) . '.' . $image->guessExtension();
            //on le déplace dans le dossier passé en paramètre
            $image->move($this->getParameter('users_images_directory'), $url);
            $user->setPicture($url);
            $user->setHash($this->passwordEncoder->encodePassword($user, $user->getHash()));
            $user->setUpdatedAt(new \DateTime('now'));
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($user);
            $entityManager->flush();
            $this->addFlash("success", "Votre compte a bien éte créé ! Connectez-vous maintenant");

            return $this->redirectToRoute('account_login');
        }

        return $this->render('user/new.html.twig', [
            'user' => $user,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{slug}", name="user_show", methods={"GET"})
     */
    public function show(User $user): Response
    {
        return $this->render('user/show.html.twig', [
            'user' => $user,
        ]);
    }

        /**
         *
         * @Route("/{slug}/edit", name="user_edit", methods={"GET","DELETE","POST"})
         * @Security("is_granted('ROLE_USER') or user === user.getSlug()",
        message="Ce profil ne vous appartient pas,vous ne pouvez pas le modifier !")
         * @param Request $request
         * @return Response
         */
    public function edit(Request $request, User $user): Response
    {
        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $picture = $user->getPicture();
            $user->setHash($this->passwordEncoder->encodePassword($user, $user->getHash()));
           unlink($this->getParameter('users_images_directory').'/'.$picture);

            $image = $form->get('picture')->getData();
            $url = md5(uniqid()) . '.' . $image->guessExtension();
            $image->move($this->getParameter('users_images_directory'), $url);
            $user->setPicture($url);

            $user->setUpdatedAt(new \DateTime('now'));
            $this->getDoctrine()->getManager()->flush();
            $this->addFlash("success", "Vos modifications ont été mises à jour !");

            return $this->redirectToRoute('user_index');
        }

        return $this->render('user/edit.html.twig', [
            'user' => $user,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="user_delete", methods={"DELETE"})
     * @param Request $request
     * @param User $user
     * @return Response
     */
    public function delete(Request $request, User $user): Response
    {
        if ($this->isCsrfTokenValid('delete'.$user->getId(), $request->request->get('_token'))) {
            $picture = $user->getPicture();
            //Si on efface une image de la base de donnéeé, on l'efface également en local
            unlink($this->getParameter('users_images_directory').'/'.$picture);
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($user);
            $entityManager->flush();
        }
        return $this->redirectToRoute('user_index');
    }


}

templates/user/_delete_form.html.twig
<form method="post" action="{{ path('user_delete', {'id': user.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ user.id) }}">
    <button class="btn btn-danger mt-1">
        <i class="fas fa-trash"></i>
    </button>
</form>

templates/user/_form.html.twig
{{ form_start(form,{'attr': {'novalidate': 'novalidate'}}) }}
    {{ form_widget(form) }}
    <button class="btn btn-success">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/user/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit User{% endblock %}

{% block body %}
    <div class="container">
        <h1>Edit User</h1>

        {{ include('user/_form.html.twig', {'button_label': 'Update'}) }}

        <a class="btn btn-info mt-2" href="{{ path('user_index') }}">
            <i class="fas fa-arrow-circle-left"></i>
        </a>

        {{ include('user/_delete_form.html.twig') }}
    </div>
{% endblock %}

templates/user/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}User index{% endblock %}

{% block body %}
    <div class="container-fluid mt-2">
        <h1 class="text-info text-center">User index</h1>

        <table class="table table-hover table-dark">
            <thead>
            <tr>
                <th>Id</th>
                <th>FirstName</th>
                <th>LastName</th>
                <th>Email</th>
                <th>Picture</th>
                {#<th>Hash</th>#}
                <th>Intro</th>
                <th>Presentation</th>
                <th>Slug</th>
                <th>Updated_at</th>
                <th>actions</th>
            </tr>
            </thead>
            <tbody>
            {% for user in users %}
                <tr>
                    <td>{{ user.id }}</td>
                    <td>{{ user.firstName }}</td>
                    <td>{{ user.lastName }}</td>
                    <td>{{ user.email }}</td>
                    <td>
                        <img class="image_border avatar-mini" src="/usersimages/{{ user.picture }}"
                             alt="imade de l'utilisateur">
                    </td>
                    {# <td>{{ user.hash }}</td> #}
                    <td>{{ user.intro }}</td>
                    <td>{{ user.presentation }}</td>
                    <td>{{ user.slug }}</td>
                    <td>{{ user.updatedAt ? user.updatedAt|date('Y-m-d H:i:s') : '' }}</td>
                    <td>
                        <a class="btn btn-primary"
                           href="{{ path('user_show', {'slug': user.slug}) }}">
                            <i class="fas fa-eye"></i>
                        </a>
                        <a class="btn btn-danger mt-2"
                           href="{{ path('user_edit', {'slug': user.slug}) }}">
                            <i class="fas fa-edit"></i></a>
                    </td>
                </tr>
            {% else %}
                <tr>
                    <td colspan="11">no records found</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        {% include 'admin/partials/pagination.html.twig' with {'route' : 'user_index'} %}

        {#        <a class="btn btn-primary" href="{{ path('user_new') }}">Create new</a>#}
    </div>
{% endblock %}

templates/user/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New User{% endblock %}

{% block body %}
    <div class="container m-auto">
        <h1>Create new User</h1>

        {{ include('user/_form.html.twig') }}

        <a href="{{ path('user_index') }}"><i class="fas fa-arrow-circle-left"></i></a>
    </div>
{% endblock %}

templates/user/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}User{% endblock %}

{% block body %}
    <div class="container">
        <h1 class="text-center text-info py-3">User</h1>
        <div class="row">
            <div class="col-3 text-center">
                <a href="/usersimages/{{ user.picture }}" alt="{{ user.firstName }}">
                    <img class="mb-3" id="avatar" src="/usersimages/{{ user.picture }}" alt="{{ user.firstName }}">
                </a>
                <br>
                <span class="badge badge-primary">{{ user.annonces |length }} annonce(s).</span>
            </div>
            <div class="col-9">
                <h1>{{ user.fullName }}</h1>
            </div>
        </div>

    {{ user.presentation }}
        <hr>

        <h1>Les annonces de {{ user.fullName }} </h1>

        {% if user.annonces | length > 0 %}
            <div class="row">
            {% for ads in user.annonces  %}
                <div class="col-md-4">
                    <div class="card badge-light mb-3">
                        <div class="card-header text-center">
                            {{ ads.nombreAd }} {{ ads.title }}, <strong>{{ ads.price }}&euro; chacun</strong><br>
                            <small>Pas encore noté</small>
                        </div>
                        <a href="/uploads/{{ ads.image }}">
                            <img src="/uploads/{{ ads.image }}" alt="Image du téléphone" style="width:100% ; height:250px ;display:block">
                        </a>
                        <div class="card-body">
                            <h4 class="card-title">{{ ads.title }} </h4>
                            <p class="card-text">{{ ads.introduction }}</p>
                            <a class="btn btn-secondary" href="{{ path('annonces_show', {'slug':ads.slug}) }}" role="button">
                                <i class="fas fa eye"></i>
                            </a>
                        </div>
                    </div>
                </div>
            {% endfor %}
            </div>
            {% else %}
            <div class="alert alert-warning">
                <h1>{{ user.fullName }} n'a pas d'annonces pour l'instant !</h1>
            </div>

        {% endif %}

{#<td>{{ user.updatedAt ? user.updatedAt|date('Y-m-d H:i:s') : '' }}</td>#}


        {#href="{{ path('user_index') }}">back to list</a>#}

        <p>
            <a class="btn btn-primary" href="{{ path('user_edit', {'slug': user.slug}) }}">
                <i class="fas fa-edit"></i>
            </a>
            <a class="btn btn-primary" href="{{ path('profole_password')}}">Update Password</a>

        {{ include('user/_delete_form.html.twig') }}
        </p>



    </div>
{% endblock %}